Create GitHub Actions for linting, testing and releasing
hifis-net/ansible-role-gitlab pull request #2
Opened 2022-04-07 12:07 UTC by christianhueserhzdr

Extend CI pipeline to do the linting and testing on each pull request and on each merging into branch main and tagging releases and to do the releasing on each tag created.

In preparation of the relocation from GitLab.com to GitHub as described in: https://gitlab.com/hifis/ansible/gitlab-role/-/issues/49

2022-04-07 13:11 UTC, christianhueserhzdr commented
Dear Tobias @tobiashuste, I prepared the GitHub Actions to move developments from GitLab to GitHub. Could you please have a look whether all is fine and I did not miss anything? Thanks for your review.

2022-04-08 06:06 UTC, tobiashuste requested changes
Thanks for implementing this! I found out about the caching feature of the `setup-python` action which is a bit simpler to apply. This is why I suggested changes to make use of it.

Could you please also add the Changelog entry?

2022-04-08 06:06 UTC, tobiashuste commented on .github/workflows/ci.yml
> +  PIP_CACHE_DIR: ~/.cache/pip
I just learned about the caching feature of the `setup-python` action and suggest to use this instead.

```suggestion
```

2022-04-08 06:06 UTC, tobiashuste commented on .github/workflows/prepare-action/action.yml
> +      shell: bash
```suggestion
```

2022-04-08 06:06 UTC, tobiashuste commented on .github/workflows/prepare-action/action.yml
> +  steps:
```suggestion
  steps:
    - name: Install pipenv
      run: pipx install pipenv
      shell: bash

```

2022-04-08 06:06 UTC, tobiashuste commented on .github/workflows/prepare-action/action.yml
> +        python-version: '3.9'
According to https://github.com/actions/setup-python#caching-packages-dependencies

```suggestion
        python-version: '3.9'
        cache: 'pipenv'
```

2022-04-11 06:27 UTC, tobiashuste commented
@christianhueserhzdr Is this ready from your side?

2022-04-11 07:07 UTC, christianhueserhzdr commented
> @christianhueserhzdr Is this ready from your side?

Dear Tobias @tobiashuste, from my side I incorporated your suggestions, added the Dependabot to the GitHub Actions and removed the obsolete GitLab CI file. Could you please review again? Thanks.

2022-04-11 07:14 UTC, tobiashuste approved these changes
Thanks, @christianhueserhzdr for implementing this :shipit:

2022-04-11 07:14 UTC, merged