Add Debian 11 (bullseye) as platform
hifis-net/ansible-role-gitlab pull request #50
Opened 2022-10-12 13:18 UTC by flyinggecko

Hi,

This PR adds Debian 11 as target platform for this role.

Bests

2022-10-14 15:14 UTC, tobiashuste requested changes
Dear @flyinggecko, thanks for providing this. Very much appreciated!

Would you please add debian 11 to the GitHub Actions pipelline as well. This can be done by adding `debian11` to this list:

https://github.com/hifis-net/ansible-role-gitlab/blob/657524215d6a8b0b0cdfcb14d2d7980dc0ea8e3f/.github/workflows/ci.yml#L56-L60

Thanks :smiley:

2022-10-14 15:14 UTC, tobiashuste commented on meta/main.yml
> +        - 11
`ansible-lint` expects a string here.

```suggestion
        - "11"
```

2022-10-20 19:06 UTC, flyinggecko commented
Hi,

I've added all the requested changes.

Bests ;)

2022-10-21 05:17 UTC, tobiashuste approved these changes
Thanks, @flyinggecko :rocket: Will create a new release soon.

2022-10-21 05:18 UTC, merged